### ISSUE TITLE
How to download software in dnanexus?

### ISSUE THREAD

**Issue by wojiaolianer** [pjgreer/ukb-rap-tools#10]
Hello Phil Greer,
I notice that you download rvtest in analysis. And I get in trouble using downloaded software, so looking for your help. Here is my code. The error is can't find magma.

`magma="wget https://ctg.cncr.nl/software/MAGMA/prog/magma_v1.10.zip; \
unzip magma_v1.10.zip; \
magma --annotate --snp-loc ukb23158_merged_RHTN_QC1.bim --gene-loc NCBI38.gene.loc --out ukb23158_merged_RHTN_QC1"

  dx run swiss-army-knife \
 -iin="${project}:/data/magma/NCBI38.gene.loc" \
 -iin="${project}:/data/QC1/ukb23158_merged_RHTN_QC1.bim" \
 -icmd="${magma}" \
 --tag="PLINK_QC1" --instance-type "mem1_ssd1_v2_x4"\
 --destination="${project}:/data/magma/" --brief --yes`

**Comment by pjgreer** [comment]
The problem is when you execute magma.  You need the path to the executable because by default the current directory is not on your path. Also remember that that you will copy the magma software to the RAP every time you run this, so you may want to delete that after the run finishes.

magma="wget https://ctg.cncr.nl/software/MAGMA/prog/magma_v1.10.zip;
unzip magma_v1.10.zip;
./magma --annotate --snp-loc ukb23158_merged_RHTN_QC1.bim --gene-loc NCBI38.gene.loc --out ukb23158_merged_RHTN_QC1"

**Comment by wojiaolianer** [comment]
> The problem is when you execute magma. You need the path to the executable because by default the current directory is not on your path. Also remember that that you will copy the magma software to the RAP every time you run this, so you may want to delete that after the run finishes.
> .
> magma="wget https://ctg.cncr.nl/software/MAGMA/prog/magma_v1.10.zip; unzip magma_v1.10.zip; ./magma --annotate --snp-loc ukb23158_merged_RHTN_QC1.bim --gene-loc NCBI38.gene.loc --out ukb23158_merged_RHTN_QC1"

Thanks, it run sucessful, your suggestion do a lot help.
