### ISSUE TITLE
what is the difference between these files

### ISSUE THREAD

**Issue by TrumanZYX** [pjgreer/ukb-rap-tools#12]
Dear,
   do you know if it is possible

**Comment by pjgreer** [comment]
Based on the info here:
https://biobank.ndph.ox.ac.uk/showcase/label.cgi?id=170

ukb23157 is in pVCF format (.vcf.gz .vcf.gz.tbi)
ukb23158 is in plink format (.bed .bim .fam)
ukb23159 is in BGEN format (.bgen .bgi, .sample)

Both the bgen and the plink format files were created directly from the .pVCF file. Therefore, they should not materially differ from each other. Other than the bgen and pVCF will have data on read depth and QC that the plink file discarded.

Plink and REGENIE both prefer data file in plink format (either the older  bed/bim/fam or the newer pgen/pvar/psam format). Both programs can read the .bgen format, but it is slower because they have to convert it internally to plink format. 

If you are doing this to filter the data on QC or read depth, then you should make an intermediate script where you filter the bgen or pVCF file and save it out to a plink file for use in the actual analysis.
